$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
code: .
command: >-
  python train.py
  --data ${{inputs.data}}
  --learning_rate ${{inputs.learning_rate}}
  --n_estimators ${{inputs.n_estimators}}
  --registered_model_name ${{inputs.registered_model_name}}
inputs:
  data: 
    type: uri_folder 
    path: azureml:realtor-data-clean@latest
  learning_rate: 0.1
  n_estimators: 100
  registered_model_name: realtor-model
environment: azureml:AzureML-sklearn-0.24-ubuntu18.04-py37-cpu@latest
# compute: azureml:computer456
experiment_name: model-train-job
description: Training job via Github actions