$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
code: .
command: >-
  python train.py
  --data ${{inputs.data}}
  --learning_rate ${{inputs.learning_rate}}
  --n_estimators ${{inputs.n_estimators}}
  --registered_model_name ${{inputs.registered_model_name}}
inputs:
  data: 
    type: uri_file 
    path: azureml:realtor-data-clean@latest
  learning_rate: 0.1
  n_estimators: 100
  registered_model_name: realtor-model
environment: azureml://registries/azureml/environments/sklearn-1.1/versions/26
experiment_name: model-train-job
description: Training job via Github actions